default: &default
  adapter: postgresql
  encoding: SQL_ASCII
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
  host:     <%= ENV['IP'] %>

development:
  <<: *default
  database: flickr-search_development

test:
  <<: *default
  database: flickr-search_test

staging:
  <<: *default
  database: flcikr-search_staging

production:
  <<: *default
  database: flickr-search_production
  username: flickr-search
  password: <%= ENV['FLICKR-SEARCH_DATABASE_PASSWORD'] %>
